### ISSUE TITLE
Bots

### ISSUE THREAD

**Issue by unshame** [Rasie1/CG2016Game#42]
Добавил базовую поддержку ботов - их можно спавнить из консоли при помощи команды addbots(кол-во). Спавнить их может любой игрок. Боты принадлежат тому, кто их заспавнил, он же и будет обрабатывать их поведение.
Помимо собственно добавления ботов сейчас сделана раздача информации о них всем игрокам при создании новых ботов или когда кто-то подключился на сервер. Также, когда кто-то отключается, все его боты корректно уничтожаются на сервере и на всех клиентах.
Владелец ботов будет обрабатывать их поведение через новую функцию Character.updateBot (по типу Character.update), а вот все остальное будет сделано через уже существующие функции.
Алсо у Character теперь есть isBot и owner, которые отличают настоящих игроков от ботов.
Что надо сделать:
1.Поведение ботов - это AI и правильная реакция на окружение, дамаг, пикапы и ит.д.
2.Передача информации о действиях ботов на сервер, хранение ее на сервере и раздача другим клиентам
3.Прием и обработка информации клиентами о ботах чужих игроков
4.Что-то еще?

**Comment by Rasie1** [comment]
nice job!
